### ISSUE TITLE
No available version compatible with the installed Inkdrop version: 3.10.6

### ISSUE THREAD

**Issue by inputsh** [inkdropapp/inkdrop-spell-checker#1]
So, trying to do `ipm install spell-check` gave me the following error:

    No available version compatible with the installed Inkdrop version: 3.10.6

Running on Ubuntu 16.04, installed via `.deb` package.

I see that you've pushed some code half a day ago, and I'm assuming it's related to this, but couldn't find anything in the issue tracker. Therefore, I'm opening this as a tracking method to know when will this plugin be compatible with the current version of Inkdrop.

**Comment by craftzdog** [comment]
Hi,

Thank you for reporting it.
As the error message says, it requires the current latest version (v3.11.0) of the app because I added some APIs for this plugin.
If you have an issue with v3.11.0, please let me know.
