### ISSUE TITLE
Adding Keybindings

### ISSUE THREAD

**Issue by Griizz** [inkdropapp/inkdrop-spell-checker#13]
Adding keybindings to quickly enable/disable or change languages is probably already possible.
I'm just not sure about the specific syntax. Is it possible to add a short section to the README for this?

**Comment by craftzdog** [comment]
You can make a command to toggle the package.

```js
if (inkdrop.packages.isPackageActive('spell-checker')) {
  inkdrop.packages.disablePackage('spell-checker')
} else {
  inkdrop.packages.enablePackage('spell-checker')
}
```

Check out the documentation for more detail: https://docs.inkdrop.app/manual/the-init-file
