### ISSUE TITLE
Language settings does not show

### ISSUE THREAD

**Issue by wilomgfx** [inkdropapp/inkdrop-spell-checker#4]
Currently running Inkdrop 4.3.4 on macOs Mojave.
<img width="836" alt="image" src="https://user-images.githubusercontent.com/6611491/66610976-237eba00-eb8b-11e9-9bdb-0454c257031c.png">

**Comment by craftzdog** [comment]
Thanks for reporting! Yes, I'm aware of that and have fixed in v4.4.0-beta.1.
If you are a paid user, you can try it from here:
http://my.inkdrop.app/download/beta
