### ISSUE TITLE
Port the spell checker to the mobile version of inkdrop

### ISSUE THREAD

**Issue by AthulMuralidhar** [inkdropapp/inkdrop-spell-checker#5]
- Firstly, I am super happy about ink drop, functionality and otherwise. It's the whole package, nice aesthetics (+vim support, woot!). 
- There's only one thing I miss in the mobile version of the app - the spell checker, is there a way to port the plugin to mobile devices? is it in the roadmap? 
- maybe we can just make a generic way to port plugins to mobile?

cheers and keep up the good work 😃

**Comment by craftzdog** [comment]
Hi. Yes it's planned in the roadmap here, please check out!

https://blog.inkdrop.info/the-roadmap-of-inkdrop-vol-5-251c3997bb74

**Comment by AthulMuralidhar** [comment]
lets close this right? @craftzdog

**Comment by craftzdog** [comment]
Sure
