### ISSUE TITLE
Failed to load the spell-checker package

### ISSUE THREAD

**Issue by usamao** [inkdropapp/inkdrop-spell-checker#9]
After I updated this plugin via the preference screen of Inkdrop, v2.1.0 was installed and spell checker didn't work with the following warning.
```
Failed to load the spell-checker package
Cannot use import statement outside a module
```
My devices are MacBook Pro (15-inch, 2018) Catalina 10.15.7 and MacBook Pro (15-inch, 2018) Monterey 12.0.1.
Before updating, spell checker worked well.
Can you check this?

**Comment by craftzdog** [comment]
Can you try v2.1.1?

**Comment by usamao** [comment]
I checked new version and spell checker works well at v2.1.1.
Thank you for your quick addressing.
